check:
	echo "Working"

compile:
	echo "Compiling Login.cpp"
	g++ login.cpp -o Login

App:
	./Login

source:
	echo "Displaying Login.cpp info"
	cat Login.cpp

admin:
	echo "Admin Header File"
	cat Admin.h

faculty:
	echo "Displaying Faculty File"
	cat faculty.h

logincsv:
	echo "Login CSV Info"
	cat FacDAta.csv

databasecsv:
	echo "Admin Update Info"
	cat database.csv

facultycsv:
	echo "Faculty Data Info"
	cat faculty.csv

csv:
	ls *.csv

header:
	ls *.h

main:
	ls *.cpp

valid:
	cat Valid.h